export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_TOPIC_TITLES_REQUEST = 'FETCH_TOPIC_TITLES_REQUEST';
export const FETCH_TOPIC_TITLES_SUCCESS = 'FETCH_TOPIC_TITLES_SUCCESS';
export const FETCH_TOPIC_TITLES_ERROR = 'FETCH_TOPIC_TITLES_ERROR';

export const FETCH_TOPIC_ARTICLES_REQUEST = 'FETCH_TOPIC_ARTICLES_REQUEST';
export const FETCH_TOPIC_ARTICLES_SUCCESS = 'FETCH_TOPIC_ARTICLES_SUCCESS';
export const FETCH_TOPIC_ARTICLES_ERROR = 'FETCH_TOPIC_ARTICLES_ERROR';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

export const COMMENT_VOTE_REQUEST = 'COMMENT_VOTE_REQUEST';
export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS';
export const COMMENT_VOTE_ERROR = 'COMMENT_VOTE_ERROR';

