export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_TOPIC_TITLES_REQUEST = 'FETCH_TOPIC_TITLES_REQUEST';
export const FETCH_TOPIC_TITLES_SUCCESS = 'FETCH_TOPIC_TITLES_SUCCESS';
export const FETCH_TOPIC_TITLES_ERROR = 'FETCH_TOPIC_TITLES_ERROR';

export const FETCH_TOPIC_ARTICLES_REQUEST = 'FETCH_TOPIC_ARTICLES_REQUEST';
export const FETCH_TOPIC_ARTICLES_SUCCESS = 'FETCH_TOPIC_ARTICLES_SUCCESS';
export const FETCH_TOPIC_ARTICLES_ERROR = 'FETCH_TOPIC_ARTICLES_ERROR';

